name: mtg_symbology
description: "Easily display Magic: The Gathering symbols as Flutter SVG widgets."
repository: https://github.com/zmuranaka/mtg_symbology
issue_tracker: https://github.com/zmuranaka/mtg_symbology/issues
version: 1.0.6

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0

dev_dependencies:
  http: ^1.6.0
  test: ^1.31.2
  very_good_analysis: ^10.3.0

flutter:
  assets:
    - assets/
